import RealEstateFour from "@/public/assets/real-estate-4.jpg";
import RealEstateOne from "@/public/assets/real-estate.jpg";
import PropertyTwo from "@/public/assets/property2.jpg";

export const propertiesData = [
  {
    id: 1,
    title: "123 Oak Avenue, Springfield",
    price: "₦350,000",
    beds: 3,
    baths: 2.5,
    area: "1800 sqft",
    tags: ["Garage", "New Build", "Smart Home"],
    image: RealEstateOne,
  },
  {
    id: 2,
    title: "101 Cedar Lane, Lakeview",
    price: "₦620,000",
    beds: 5,
    baths: 4,
    area: "3200 sqft",
    tags: ["Swimming Pool", "Gated Community"],
    image: RealEstateFour,
  },
  {
    id: 3,
    title: "45 Maple Street, Downtown",
    price: "₦450,000",
    beds: 4,
    baths: 3,
    area: "2400 sqft",
    tags: ["City View", "Balcony"],
    image: PropertyTwo,
  },
  {
    id: 4,
    title: "78 Pine Crescent, Riverside",
    price: "₦500,000",
    beds: 3,
    baths: 2,
    area: "1900 sqft",
    tags: ["Garden", "Garage"],
    image: RealEstateOne,
  },
  {
    id: 5,
    title: "210 Birch Road, Hilltop",
    price: "₦750,000",
    beds: 6,
    baths: 5,
    area: "3800 sqft",
    tags: ["Luxury", "Private Pool", "Smart Home"],
    image: RealEstateFour,
  },
  {
    id: 6,
    title: "92 Willow Lane, Greenfield",
    price: "₦320,000",
    beds: 2,
    baths: 2,
    area: "1500 sqft",
    tags: ["Eco-Friendly", "Solar Panels"],
    image: PropertyTwo,
  },
  {
    id: 7,
    title: "301 Elm Street, Uptown",
    price: "₦600,000",
    beds: 4,
    baths: 3.5,
    area: "2600 sqft",
    tags: ["City View", "Modern Design"],
    image: RealEstateOne,
  },
  {
    id: 8,
    title: "15 Aspen Drive, Lakeview",
    price: "₦420,000",
    beds: 3,
    baths: 2,
    area: "2100 sqft",
    tags: ["Lake View", "Deck"],
    image: RealEstateFour,
  },
  {
    id: 9,
    title: "65 Walnut Avenue, Westend",
    price: "₦540,000",
    beds: 4,
    baths: 3,
    area: "2500 sqft",
    tags: ["Home Office", "Smart Lock"],
    image: PropertyTwo,
  },
  {
    id: 10,
    title: "320 Palm Street, Midtown",
    price: "₦700,000",
    beds: 5,
    baths: 4,
    area: "3400 sqft",
    tags: ["Open Floor Plan", "Luxury Finish"],
    image: RealEstateOne,
  },
  {
    id: 11,
    title: "19 Cypress Court, Woodland",
    price: "₦390,000",
    beds: 3,
    baths: 2,
    area: "1800 sqft",
    tags: ["Green Space", "Outdoor Patio"],
    image: RealEstateFour,
  },
  {
    id: 12,
    title: "50 Chestnut Boulevard, Seaside",
    price: "₦800,000",
    beds: 6,
    baths: 5.5,
    area: "4200 sqft",
    tags: ["Ocean View", "Private Dock", "Luxury"],
    image: PropertyTwo,
  },
  {
    id: 13,
    title: "222 Oakridge Lane, Forest Hill",
    price: "₦360,000",
    beds: 3,
    baths: 2,
    area: "1900 sqft",
    tags: ["Quiet Neighborhood", "Fireplace"],
    image: RealEstateOne,
  },
  {
    id: 14,
    title: "12 Magnolia Street, Downtown",
    price: "₦580,000",
    beds: 4,
    baths: 3,
    area: "2700 sqft",
    tags: ["City Lights", "High Ceilings"],
    image: RealEstateFour,
  },
  {
    id: 15,
    title: "303 Aspen Grove, Lakeside",
    price: "₦470,000",
    beds: 3,
    baths: 2.5,
    area: "2200 sqft",
    tags: ["Scenic View", "Private Garden"],
    image: PropertyTwo,
  },
  {
    id: 16,
    title: "8 Maplewood Lane, Hillcrest",
    price: "₦510,000",
    beds: 4,
    baths: 3.5,
    area: "2600 sqft",
    tags: ["Smart Lighting", "Garage"],
    image: RealEstateOne,
  },
  {
    id: 17,
    title: "121 Redwood Avenue, Eastwood",
    price: "₦680,000",
    beds: 5,
    baths: 4.5,
    area: "3500 sqft",
    tags: ["Modern Kitchen", "Luxury"],
    image: RealEstateFour,
  },
  {
    id: 18,
    title: "40 Maple Crossing, Bayview",
    price: "₦420,000",
    beds: 3,
    baths: 2,
    area: "2100 sqft",
    tags: ["Near Beach", "Balcony"],
    image: PropertyTwo,
  },
  {
    id: 19,
    title: "77 Birchwood Drive, Highlands",
    price: "₦560,000",
    beds: 4,
    baths: 3.5,
    area: "2800 sqft",
    tags: ["Mountain View", "Fireplace"],
    image: RealEstateOne,
  },
  {
    id: 20,
    title: "88 Willow Park, Northgate",
    price: "₦620,000",
    beds: 5,
    baths: 4,
    area: "3300 sqft",
    tags: ["Energy Efficient", "Smart Home"],
    image: RealEstateFour,
  },
  {
    id: 21,
    title: "14 Riverbend Lane, Rivertown",
    price: "₦500,000",
    beds: 3,
    baths: 2.5,
    area: "2000 sqft",
    tags: ["River View", "Garden"],
    image: PropertyTwo,
  },
  {
    id: 22,
    title: "90 Cedar Heights, Greenfield",
    price: "₦430,000",
    beds: 3,
    baths: 2,
    area: "1900 sqft",
    tags: ["Eco Home", "Solar Panels"],
    image: RealEstateOne,
  },
  {
    id: 23,
    title: "55 Ocean Breeze, Seaview",
    price: "₦900,000",
    beds: 7,
    baths: 6,
    area: "4800 sqft",
    tags: ["Luxury", "Oceanfront", "Private Dock"],
    image: RealEstateFour,
  },
];
